services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: pet_adoption_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pet_adoption_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  matching-service:
    build:
      context: ./matching-service
    container_name: matching-service
    environment:
      SERVER_PORT: 8081
    ports:
      - "8081:8081"

  pet-adoption-service:
    build:
      context: ./pet-adoption-service
    container_name: pet-adoption-service
    depends_on:
      postgres:
        condition: service_healthy
      matching-service:
        condition: service_started
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pet_adoption_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      MATCHING_SERVICE_URL: http://matching-service:8081
    ports:
      - "8080:8080"
volumes:
  postgres_data:
